modstitch.platform=moddevgradle-legacy

mcVersion=1.20.1
packFormat=15

deps.forge=1.20.1-47.4.0
parchment.version=2023.09.03

# Forge 1.20.1 dependencies
deps.yacl=3.6.6+1.20.1-forge
deps.fancyMenu=3.2.3-1.20.1-forge
deps.mixinExtras=0.5.0-beta.4
deps.sdl3Target=3.1.9.075c033
deps.sdl34jBuild=66
deps.hid4java=0.8.0
deps.quiltParsers=0.3.0
deps.steamdeck4j=1.1.7

meta.mcDep=[1.20.1,1.20.2)
meta.loaderDep=[47,)
